-- Enable UUID extension if not already
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- profiles table
CREATE TABLE profiles (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('driver', 'dispatch', 'admin')),
    is_premium BOOLEAN DEFAULT FALSE
);

-- jobs table
CREATE TABLE jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    user_id UUID REFERENCES profiles(id) NOT NULL,  -- dispatch user who created
    driver_id UUID REFERENCES profiles(id),  -- assigned driver
    status TEXT NOT NULL CHECK (status IN ('pending', 'in_progress', 'completed')) DEFAULT 'pending',
    expense NUMERIC DEFAULT 0,
    revenue NUMERIC DEFAULT 0,
    latitude NUMERIC,
    longitude NUMERIC,
    proof_url TEXT,
    is_boosted BOOLEAN DEFAULT FALSE,
    boost_expires_at TIMESTAMP,
    completed_at TIMESTAMP
);

-- payments table
CREATE TABLE payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES profiles(id) NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('subscription', 'boost')),
    amount NUMERIC NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- translations table
CREATE TABLE translations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    language TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Profiles RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Users can view own profile
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);

-- Users can update own profile (limited fields)
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Admins full access to profiles
CREATE POLICY "Admins full access to profiles" ON profiles USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- Jobs RLS
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Drivers see pending or assigned jobs
CREATE POLICY "Drivers see pending or assigned jobs" ON jobs FOR SELECT USING (
    (status = 'pending' OR driver_id = auth.uid()) AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'driver')
);

-- Drivers claim pending jobs
CREATE POLICY "Drivers claim pending jobs" ON jobs FOR UPDATE USING (
    status = 'pending' AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'driver')
);

-- Drivers update assigned jobs
CREATE POLICY "Drivers update assigned jobs" ON jobs FOR UPDATE USING (
    driver_id = auth.uid() AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'driver')
);

-- Dispatch insert jobs
CREATE POLICY "Dispatch insert jobs" ON jobs FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'dispatch')
);

-- Dispatch update own jobs
CREATE POLICY "Dispatch update own jobs" ON jobs FOR UPDATE USING (
    user_id = auth.uid() AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'dispatch')
);

-- Dispatch see own jobs
CREATE POLICY "Dispatch see own jobs" ON jobs FOR SELECT USING (
    user_id = auth.uid() AND
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'dispatch')
);

-- Admins full access – using current user's role directly from auth context
CREATE POLICY "Admins have full access to profiles"
ON profiles
FOR ALL
USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
)
WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
);

-- Payments RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Users manage own payments
CREATE POLICY "Users manage own payments" ON payments FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- Admins full access to payments
CREATE POLICY "Admins full access to payments" ON payments USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- Translations public read
ALTER TABLE translations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read translations" ON translations FOR SELECT USING (true);

-- Insert translations
INSERT INTO translations (language, key, value) VALUES
('en', 'login', 'Login'),
('en', 'email', 'Email'),
('en', 'password', 'Password'),
('en', 'sign_up', 'Sign Up'),
('en', 'sign_in', 'Sign In'),
('en', 'logout', 'Logout'),
('en', 'dashboard', 'Dashboard'),
('en', 'earnings', 'Earnings'),
('en', 'boosts', 'Boosts'),
('en', 'premium', 'Premium'),
('en', 'admin_panel', 'Admin Panel'),
('en', 'create_job', 'Create Job'),
('en', 'update_job', 'Update Job'),
('en', 'title', 'Title'),
('en', 'expense', 'Expense'),
('en', 'revenue', 'Revenue'),
('en', 'latitude', 'Latitude'),
('en', 'longitude', 'Longitude'),
('en', 'status', 'Status'),
('en', 'pending', 'Pending'),
('en', 'in_progress', 'In Progress'),
('en', 'completed', 'Completed'),
('en', 'claim', 'Claim Job'),
('en', 'mark_completed', 'Mark Completed'),
('en', 'total_earnings', 'Total Earnings'),
('en', 'subscribe_premium', 'Subscribe to Premium'),
('en', 'boost_job', 'Boost Job'),
('en', 'job_list', 'Job List'),
('en', 'assigned_jobs', 'Assigned Jobs'),
('en', 'completed_jobs', 'Completed Jobs'),
('en', 'clear_all_jobs', 'Clear All Jobs'),
('en', 'job_status_counts', 'Job Status Counts'),
('en', 'success', 'Success'),
('en', 'failure', 'Failure'),
('en', 'payment_success', 'Payment Successful'),
('en', 'payment_failure', 'Payment Failed'),
('en', 'select_language', 'Select Language'),
('en', 'role_driver', 'Driver'),
('en', 'role_dispatch', 'Dispatch'),
('en', 'role_admin', 'Admin'),
('en', 'my_jobs', 'My Jobs'),
('en', 'all_jobs', 'All Jobs'),
('en', 'boost_expires', 'Boost Expires'),
('en', 'proof_url', 'Proof URL'),
('en', 'is_boosted', 'Boosted'),
('en', 'completed_at', 'Completed At'),
('sw', 'login', 'Ingia'),
('sw', 'email', 'Barua pepe'),
('sw', 'password', 'Neno la siri'),
('sw', 'sign_up', 'Jisajili'),
('sw', 'sign_in', 'Ingia'),
('sw', 'logout', 'Toka'),
('sw', 'dashboard', 'Dashibodi'),
('sw', 'earnings', 'Mapato'),
('sw', 'boosts', 'Nyongeza'),
('sw', 'premium', 'Premium'),
('sw', 'admin_panel', 'Paneli ya Admin'),
('sw', 'create_job', 'Unda Kazi'),
('sw', 'update_job', 'Sasisha Kazi'),
('sw', 'title', 'Kichwa'),
('sw', 'expense', 'Gharama'),
('sw', 'revenue', 'Mapato'),
('sw', 'latitude', 'Latitudo'),
('sw', 'longitude', 'Longitudo'),
('sw', 'status', 'Hali'),
('sw', 'pending', 'Inasubiri'),
('sw', 'in_progress', 'Inaendelea'),
('sw', 'completed', 'Imekamilika'),
('sw', 'claim', 'Dai Kazi'),
('sw', 'mark_completed', 'Tia Alama Imekamilika'),
('sw', 'total_earnings', 'Mapato Yote'),
('sw', 'subscribe_premium', 'Jisajili Premium'),
('sw', 'boost_job', 'Nyongeza Kazi'),
('sw', 'job_list', 'Orodha ya Kazi'),
('sw', 'assigned_jobs', 'Kazi Zilizotolewa'),
('sw', 'completed_jobs', 'Kazi Zilizokamilika'),
('sw', 'clear_all_jobs', 'Futa Kazi Zote'),
('sw', 'job_status_counts', 'Idadi ya Hali ya Kazi'),
('sw', 'success', 'Mafanikio'),
('sw', 'failure', 'Kushindwa'),
('sw', 'payment_success', 'Malipo Yamefanikiwa'),
('sw', 'payment_failure', 'Malipo Yameshindwa'),
('sw', 'select_language', 'Chagua Lugha'),
('sw', 'role_driver', 'Dereva'),
('sw', 'role_dispatch', 'Msimamizi'),
('sw', 'role_admin', 'Admin'),
('sw', 'my_jobs', 'Kazi Zangu'),
('sw', 'all_jobs', 'Kazi Zote'),
('sw', 'boost_expires', 'Nyongeza Inaisha'),
('sw', 'proof_url', 'URL ya Uthibitisho'),
('sw', 'is_boosted', 'Imenyongezwa'),
('sw', 'completed_at', 'Imekamilika Saa'),
('de', 'login', 'Anmelden'),
('de', 'email', 'E-Mail'),
('de', 'password', 'Passwort'),
('de', 'sign_up', 'Registrieren'),
('de', 'sign_in', 'Anmelden'),
('de', 'logout', 'Abmelden'),
('de', 'dashboard', 'Dashboard'),
('de', 'earnings', 'Einnahmen'),
('de', 'boosts', 'Boosts'),
('de', 'premium', 'Premium'),
('de', 'admin_panel', 'Admin-Panel'),
('de', 'create_job', 'Job erstellen'),
('de', 'update_job', 'Job aktualisieren'),
('de', 'title', 'Titel'),
('de', 'expense', 'Ausgaben'),
('de', 'revenue', 'Einnahmen'),
('de', 'latitude', 'Breitengrad'),
('de', 'longitude', 'Längengrad'),
('de', 'status', 'Status'),
('de', 'pending', 'Ausstehend'),
('de', 'in_progress', 'In Bearbeitung'),
('de', 'completed', 'Abgeschlossen'),
('de', 'claim', 'Job beanspruchen'),
('de', 'mark_completed', 'Als abgeschlossen markieren'),
('de', 'total_earnings', 'Gesamteinnahmen'),
('de', 'subscribe_premium', 'Premium abonnieren'),
('de', 'boost_job', 'Job boosten'),
('de', 'job_list', 'Job-Liste'),
('de', 'assigned_jobs', 'Zugewiesene Jobs'),
('de', 'completed_jobs', 'Abgeschlossene Jobs'),
('de', 'clear_all_jobs', 'Alle Jobs löschen'),
('de', 'job_status_counts', 'Job-Status-Zählungen'),
('de', 'success', 'Erfolg'),
('de', 'failure', 'Fehler'),
('de', 'payment_success', 'Zahlung erfolgreich'),
('de', 'payment_failure', 'Zahlung fehlgeschlagen'),
('de', 'select_language', 'Sprache auswählen'),
('de', 'role_driver', 'Fahrer'),
('de', 'role_dispatch', 'Dispatcher'),
('de', 'role_admin', 'Admin'),
('de', 'my_jobs', 'Meine Jobs'),
('de', 'all_jobs', 'Alle Jobs'),
('de', 'boost_expires', 'Boost endet'),
('de', 'proof_url', 'Nachweis-URL'),
('de', 'is_boosted', 'Geboostet'),
('de', 'completed_at', 'Abgeschlossen am'),
('it', 'login', 'Accedi'),
('it', 'email', 'Email'),
('it', 'password', 'Password'),
('it', 'sign_up', 'Registrati'),
('it', 'sign_in', 'Accedi'),
('it', 'logout', 'Esci'),
('it', 'dashboard', 'Dashboard'),
('it', 'earnings', 'Guadagni'),
('it', 'boosts', 'Boost'),
('it', 'premium', 'Premium'),
('it', 'admin_panel', 'Pannello Admin'),
('it', 'create_job', 'Crea Lavoro'),
('it', 'update_job', 'Aggiorna Lavoro'),
('it', 'title', 'Titolo'),
('it', 'expense', 'Spesa'),
('it', 'revenue', 'Ricavo'),
('it', 'latitude', 'Latitudine'),
('it', 'longitude', 'Longitudine'),
('it', 'status', 'Stato'),
('it', 'pending', 'In attesa'),
('it', 'in_progress', 'In corso'),
('it', 'completed', 'Completato'),
('it', 'claim', 'Rivendica Lavoro'),
('it', 'mark_completed', 'Segna Completato'),
('it', 'total_earnings', 'Guadagni Totali'),
('it', 'subscribe_premium', 'Abbonati a Premium'),
('it', 'boost_job', 'Boost Lavoro'),
('it', 'job_list', 'Lista Lavori'),
('it', 'assigned_jobs', 'Lavori Assegnati'),
('it', 'completed_jobs', 'Lavori Completati'),
('it', 'clear_all_jobs', 'Cancella Tutti i Lavori'),
('it', 'job_status_counts', 'Conteggi Stato Lavori'),
('it', 'success', 'Successo'),
('it', 'failure', 'Fallimento'),
('it', 'payment_success', 'Pagamento Riuscito'),
('it', 'payment_failure', 'Pagamento Fallito'),
('it', 'select_language', 'Seleziona Lingua'),
('it', 'role_driver', 'Autista'),
('it', 'role_dispatch', 'Dispatcher'),
('it', 'role_admin', 'Admin'),
('it', 'my_jobs', 'I Miei Lavori'),
('it', 'all_jobs', 'Tutti i Lavori'),
('it', 'boost_expires', 'Boost Scade'),
('it', 'proof_url', 'URL Prova'),
('it', 'is_boosted', 'Boostato'),
('it', 'completed_at', 'Completato Il'),
('fr', 'login', 'Connexion'),
('fr', 'email', 'Email'),
('fr', 'password', 'Mot de passe'),
('fr', 'sign_up', 'S''inscrire'),
('fr', 'sign_in', 'Se connecter'),
('fr', 'logout', 'Déconnexion'),
('fr', 'dashboard', 'Tableau de bord'),
('fr', 'earnings', 'Gains'),
('fr', 'boosts', 'Boosts'),
('fr', 'premium', 'Premium'),
('fr', 'admin_panel', 'Panneau Admin'),
('fr', 'create_job', 'Créer un emploi'),
('fr', 'update_job', 'Mettre à jour l''emploi'),
('fr', 'title', 'Titre'),
('fr', 'expense', 'Dépense'),
('fr', 'revenue', 'Revenu'),
('fr', 'latitude', 'Latitude'),
('fr', 'longitude', 'Longitude'),
('fr', 'status', 'Statut'),
('fr', 'pending', 'En attente'),
('fr', 'in_progress', 'En cours'),
('fr', 'completed', 'Complété'),
('fr', 'claim', 'Revendiquer l''emploi'),
('fr', 'mark_completed', 'Marquer comme complété'),
('fr', 'total_earnings', 'Gains totaux'),
('fr', 'subscribe_premium', 'S''abonner à Premium'),
('fr', 'boost_job', 'Booster l''emploi'),
('fr', 'job_list', 'Liste des emplois'),
('fr', 'assigned_jobs', 'Emplois assignés'),
('fr', 'completed_jobs', 'Emplois complétés'),
('fr', 'clear_all_jobs', 'Effacer tous les emplois'),
('fr', 'job_status_counts', 'Comptes de statut d''emploi'),
('fr', 'success', 'Succès'),
('fr', 'failure', 'Échec'),
('fr', 'payment_success', 'Paiement réussi'),
('fr', 'payment_failure', 'Paiement échoué'),
('fr', 'select_language', 'Sélectionner la langue'),
('fr', 'role_driver', 'Chauffeur'),
('fr', 'role_dispatch', 'Dispatcher'),
('fr', 'role_admin', 'Admin'),
('fr', 'my_jobs', 'Mes emplois'),
('fr', 'all_jobs', 'Tous les emplois'),
('fr', 'boost_expires', 'Boost expire'),
('fr', 'proof_url', 'URL de preuve'),
('fr', 'is_boosted', 'Boosté'),
('fr', 'completed_at', 'Complété le'),
('pt', 'login', 'Entrar'),
('pt', 'email', 'Email'),
('pt', 'password', 'Senha'),
('pt', 'sign_up', 'Cadastrar'),
('pt', 'sign_in', 'Entrar'),
('pt', 'logout', 'Sair'),
('pt', 'dashboard', 'Painel'),
('pt', 'earnings', 'Ganhos'),
('pt', 'boosts', 'Boosts'),
('pt', 'premium', 'Premium'),
('pt', 'admin_panel', 'Painel Admin'),
('pt', 'create_job', 'Criar Trabalho'),
('pt', 'update_job', 'Atualizar Trabalho'),
('pt', 'title', 'Título'),
('pt', 'expense', 'Despesa'),
('pt', 'revenue', 'Receita'),
('pt', 'latitude', 'Latitude'),
('pt', 'longitude', 'Longitude'),
('pt', 'status', 'Status'),
('pt', 'pending', 'Pendente'),
('pt', 'in_progress', 'Em progresso'),
('pt', 'completed', 'Concluído'),
('pt', 'claim', 'Reivindicar Trabalho'),
('pt', 'mark_completed', 'Marcar como Concluído'),
('pt', 'total_earnings', 'Ganhos Totais'),
('pt', 'subscribe_premium', 'Assinar Premium'),
('pt', 'boost_job', 'Boost Trabalho'),
('pt', 'job_list', 'Lista de Trabalhos'),
('pt', 'assigned_jobs', 'Trabalhos Atribuídos'),
('pt', 'completed_jobs', 'Trabalhos Concluídos'),
('pt', 'clear_all_jobs', 'Limpar Todos os Trabalhos'),
('pt', 'job_status_counts', 'Contagens de Status de Trabalho'),
('pt', 'success', 'Sucesso'),
('pt', 'failure', 'Falha'),
('pt', 'payment_success', 'Pagamento Bem-sucedido'),
('pt', 'payment_failure', 'Pagamento Falhou'),
('pt', 'select_language', 'Selecionar Idioma'),
('pt', 'role_driver', 'Motorista'),
('pt', 'role_dispatch', 'Despachante'),
('pt', 'role_admin', 'Admin'),
('pt', 'my_jobs', 'Meus Trabalhos'),
('pt', 'all_jobs', 'Todos os Trabalhos'),
('pt', 'boost_expires', 'Boost Expira'),
('pt', 'proof_url', 'URL de Prova'),
('pt', 'is_boosted', 'Boostado'),
('pt', 'completed_at', 'Concluído Em'),
('es', 'login', 'Iniciar sesión'),
('es', 'email', 'Correo electrónico'),
('es', 'password', 'Contraseña'),
('es', 'sign_up', 'Registrarse'),
('es', 'sign_in', 'Iniciar sesión'),
('es', 'logout', 'Cerrar sesión'),
('es', 'dashboard', 'Tablero'),
('es', 'earnings', 'Ganancias'),
('es', 'boosts', 'Boosts'),
('es', 'premium', 'Premium'),
('es', 'admin_panel', 'Panel Admin'),
('es', 'create_job', 'Crear Trabajo'),
('es', 'update_job', 'Actualizar Trabajo'),
('es', 'title', 'Título'),
('es', 'expense', 'Gasto'),
('es', 'revenue', 'Ingreso'),
('es', 'latitude', 'Latitud'),
('es', 'longitude', 'Longitud'),
('es', 'status', 'Estado'),
('es', 'pending', 'Pendiente'),
('es', 'in_progress', 'En progreso'),
('es', 'completed', 'Completado'),
('es', 'claim', 'Reclamar Trabajo'),
('es', 'mark_completed', 'Marcar Completado'),
('es', 'total_earnings', 'Ganancias Totales'),
('es', 'subscribe_premium', 'Suscribirse a Premium'),
('es', 'boost_job', 'Boost Trabajo'),
('es', 'job_list', 'Lista de Trabajos'),
('es', 'assigned_jobs', 'Trabajos Asignados'),
('es', 'completed_jobs', 'Trabajos Completados'),
('es', 'clear_all_jobs', 'Borrar Todos los Trabajos'),
('es', 'job_status_counts', 'Conteos de Estado de Trabajo'),
('es', 'success', 'Éxito'),
('es', 'failure', 'Fallo'),
('es', 'payment_success', 'Pago Exitoso'),
('es', 'payment_failure', 'Pago Fallido'),
('es', 'select_language', 'Seleccionar Idioma'),
('es', 'role_driver', 'Conductor'),
('es', 'role_dispatch', 'Despachador'),
('es', 'role_admin', 'Admin'),
('es', 'my_jobs', 'Mis Trabajos'),
('es', 'all_jobs', 'Todos los Trabajos'),
('es', 'boost_expires', 'Boost Expira'),
('es', 'proof_url', 'URL de Prueba'),
('es', 'is_boosted', 'Boosted'),
('es', 'completed_at', 'Completado En'),
('nl', 'login', 'Inloggen'),
('nl', 'email', 'E-mail'),
('nl', 'password', 'Wachtwoord'),
('nl', 'sign_up', 'Aanmelden'),
('nl', 'sign_in', 'Inloggen'),
('nl', 'logout', 'Uitloggen'),
('nl', 'dashboard', 'Dashboard'),
('nl', 'earnings', 'Inkomsten'),
('nl', 'boosts', 'Boosts'),
('nl', 'premium', 'Premium'),
('nl', 'admin_panel', 'Admin Panel'),
('nl', 'create_job', 'Job aanmaken'),
('nl', 'update_job', 'Job bijwerken'),
('nl', 'title', 'Titel'),
('nl', 'expense', 'Uitgave'),
('nl', 'revenue', 'Omzet'),
('nl', 'latitude', 'Breedtegraad'),
('nl', 'longitude', 'Lengtegraad'),
('nl', 'status', 'Status'),
('nl', 'pending', 'In afwachting'),
('nl', 'in_progress', 'In behandeling'),
('nl', 'completed', 'Voltooid'),
('nl', 'claim', 'Job claimen'),
('nl', 'mark_completed', 'Markeren als voltooid'),
('nl', 'total_earnings', 'Totale inkomsten'),
('nl', 'subscribe_premium', 'Abonneren op Premium'),
('nl', 'boost_job', 'Job boosten'),
('nl', 'job_list', 'Joblijst'),
('nl', 'assigned_jobs', 'Toegewezen jobs'),
('nl', 'completed_jobs', 'Voltooide jobs'),
('nl', 'clear_all_jobs', 'Alle jobs wissen'),
('nl', 'job_status_counts', 'Job status tellingen'),
('nl', 'success', 'Succes'),
('nl', 'failure', 'Mislukking'),
('nl', 'payment_success', 'Betaling geslaagd'),
('nl', 'payment_failure', 'Betaling mislukt'),
('nl', 'select_language', 'Taal selecteren'),
('nl', 'role_driver', 'Chauffeur'),
('nl', 'role_dispatch', 'Dispatcher'),
('nl', 'role_admin', 'Admin'),
('nl', 'my_jobs', 'Mijn jobs'),
('nl', 'all_jobs', 'Alle jobs'),
('nl', 'boost_expires', 'Boost verloopt'),
('nl', 'proof_url', 'Bewijs URL'),
('nl', 'is_boosted', 'Geboost'),
('nl', 'completed_at', 'Voltooid op'),
('ru', 'login', 'Войти'),
('ru', 'email', 'Электронная почта'),
('ru', 'password', 'Пароль'),
('ru', 'sign_up', 'Зарегистрироваться'),
('ru', 'sign_in', 'Войти'),
('ru', 'logout', 'Выйти'),
('ru', 'dashboard', 'Панель управления'),
('ru', 'earnings', 'Заработки'),
('ru', 'boosts', 'Бусты'),
('ru', 'premium', 'Премиум'),
('ru', 'admin_panel', 'Панель админа'),
('ru', 'create_job', 'Создать задачу'),
('ru', 'update_job', 'Обновить задачу'),
('ru', 'title', 'Заголовок'),
('ru', 'expense', 'Расход'),
('ru', 'revenue', 'Доход'),
('ru', 'latitude', 'Широта'),
('ru', 'longitude', 'Долгота'),
('ru', 'status', 'Статус'),
('ru', 'pending', 'В ожидании'),
('ru', 'in_progress', 'В процессе'),
('ru', 'completed', 'Завершено'),
('ru', 'claim', 'Забрать задачу'),
('ru', 'mark_completed', 'Отметить завершено'),
('ru', 'total_earnings', 'Общий заработок'),
('ru', 'subscribe_premium', 'Подписаться на Премиум'),
('ru', 'boost_job', 'Буст задачи'),
('ru', 'job_list', 'Список задач'),
('ru', 'assigned_jobs', 'Назначенные задачи'),
('ru', 'completed_jobs', 'Завершенные задачи'),
('ru', 'clear_all_jobs', 'Очистить все задачи'),
('ru', 'job_status_counts', 'Счетчики статусов задач'),
('ru', 'success', 'Успех'),
('ru', 'failure', 'Неудача'),
('ru', 'payment_success', 'Оплата успешна'),
('ru', 'payment_failure', 'Оплата неудачна'),
('ru', 'select_language', 'Выбрать язык'),
('ru', 'role_driver', 'Водитель'),
('ru', 'role_dispatch', 'Диспетчер'),
('ru', 'role_admin', 'Админ'),
('ru', 'my_jobs', 'Мои задачи'),
('ru', 'all_jobs', 'Все задачи'),
('ru', 'boost_expires', 'Буст истекает'),
('ru', 'proof_url', 'URL доказательства'),
('ru', 'is_boosted', 'Бустед'),
('ru', 'completed_at', 'Завершено в'),
('uk', 'login', 'Увійти'),
('uk', 'email', 'Електронна пошта'),
('uk', 'password', 'Пароль'),
('uk', 'sign_up', 'Зареєструватися'),
('uk', 'sign_in', 'Увійти'),
('uk', 'logout', 'Вийти'),
('uk', 'dashboard', 'Панель керування'),
('uk', 'earnings', 'Заробітки'),
('uk', 'boosts', 'Бусти'),
('uk', 'premium', 'Преміум'),
('uk', 'admin_panel', 'Панель адміна'),
('uk', 'create_job', 'Створити завдання'),
('uk', 'update_job', 'Оновити завдання'),
('uk', 'title', 'Заголовок'),
('uk', 'expense', 'Витрата'),
('uk', 'revenue', 'Дохід'),
('uk', 'latitude', 'Широта'),
('uk', 'longitude', 'Довгота'),
('uk', 'status', 'Статус'),
('uk', 'pending', 'В очікуванні'),
('uk', 'in_progress', 'В процесі'),
('uk', 'completed', 'Завершено'),
('uk', 'claim', 'Забрати завдання'),
('uk', 'mark_completed', 'Позначити завершено'),
('uk', 'total_earnings', 'Загальний заробіток'),
('uk', 'subscribe_premium', 'Підписатися на Преміум'),
('uk', 'boost_job', 'Буст завдання'),
('uk', 'job_list', 'Список завдань'),
('uk', 'assigned_jobs', 'Призначені завдання'),
('uk', 'completed_jobs', 'Завершені завдання'),
('uk', 'clear_all_jobs', 'Очистити всі завдання'),
('uk', 'job_status_counts', 'Лічильники статусів завдань'),
('uk', 'success', 'Успіх'),
('uk', 'failure', 'Невдача'),
('uk', 'payment_success', 'Оплата успішна'),
('uk', 'payment_failure', 'Оплата невдала'),
('uk', 'select_language', 'Вибрати мову'),
('uk', 'role_driver', 'Водій'),
('uk', 'role_dispatch', 'Диспетчер'),
('uk', 'role_admin', 'Адмін'),
('uk', 'my_jobs', 'Мої завдання'),
('uk', 'all_jobs', 'Всі завдання'),
('uk', 'boost_expires', 'Буст закінчується'),
('uk', 'proof_url', 'URL доказу'),
('uk', 'is_boosted', 'Бустований'),
('uk', 'completed_at', 'Завершено о'),
('tr', 'login', 'Giriş'),
('tr', 'email', 'E-posta'),
('tr', 'password', 'Şifre'),
('tr', 'sign_up', 'Kaydol'),
('tr', 'sign_in', 'Giriş Yap'),
('tr', 'logout', 'Çıkış'),
('tr', 'dashboard', 'Kontrol Paneli'),
('tr', 'earnings', 'Kazançlar'),
('tr', 'boosts', 'Boostlar'),
('tr', 'premium', 'Premium'),
('tr', 'admin_panel', 'Admin Paneli'),
('tr', 'create_job', 'İş Oluştur'),
('tr', 'update_job', 'İş Güncelle'),
('tr', 'title', 'Başlık'),
('tr', 'expense', 'Gider'),
('tr', 'revenue', 'Gelir'),
('tr', 'latitude', 'Enlem'),
('tr', 'longitude', 'Boylam'),
('tr', 'status', 'Durum'),
('tr', 'pending', 'Beklemede'),
('tr', 'in_progress', 'Devam Ediyor'),
('tr', 'completed', 'Tamamlandı'),
('tr', 'claim', 'İş Talep Et'),
('tr', 'mark_completed', 'Tamamlandı Olarak İşaretle'),
('tr', 'total_earnings', 'Toplam Kazanç'),
('tr', 'subscribe_premium', 'Premium Abone Ol'),
('tr', 'boost_job', 'İş Boostla'),
('tr', 'job_list', 'İş Listesi'),
('tr', 'assigned_jobs', 'Atanan İşler'),
('tr', 'completed_jobs', 'Tamamlanan İşler'),
('tr', 'clear_all_jobs', 'Tüm İşleri Temizle'),
('tr', 'job_status_counts', 'İş Durum Sayıları'),
('tr', 'success', 'Başarı'),
('tr', 'failure', 'Başarısızlık'),
('tr', 'payment_success', 'Ödeme Başarılı'),
('tr', 'payment_failure', 'Ödeme Başarısız'),
('tr', 'select_language', 'Dil Seç'),
('tr', 'role_driver', 'Sürücü'),
('tr', 'role_dispatch', 'Gönderici'),
('tr', 'role_admin', 'Admin'),
('tr', 'my_jobs', 'İşlerim'),
('tr', 'all_jobs', 'Tüm İşler'),
('tr', 'boost_expires', 'Boost Bitiyor'),
('tr', 'proof_url', 'Kanıt URL'),
('tr', 'is_boosted', 'Boostlu'),
('tr', 'completed_at', 'Tamamlanma Zamanı');
